version: "3.7"
services:
  expose:
    image: beyondcodegmbh/expose-server:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8061}:${PORT}"
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    networks:
      - expose-nginx-kjm1ie
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
networks:
  expose-nginx-kjm1ie:
    name: expose-nginx-kjm1ie
    external: true
